version: 0.0
os: linux

# 배포 파일 설정
files:
  - source: /
    destination: /home/ubuntu/app/backend
    overwrite: yes

# 복사한 파일 권한 설정
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

# 배포 이후 수행 스크립트 지정
hooks:
  AfterInstall:
    - location: scripts/backend-deploy.sh #기존 애플리케이션 종료
      timeout: 180
      runas: ubuntu
