version: "3"

services:
  nginxproxy:
    image: nginx:1.18.0
    depends_on:
      - backend
    ports:
      - "80:8080"
      - "3000:3000"
    restart: always
    volumes:
      - "./backend/nginx:/etc/nginx"
      - "./frontend/dist:/usr/share/nginx/html"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    restart: always
